# Generated by Django 4.0.6 on 2022-08-02 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('others', 'Others'), ('hip hop', 'Hip Hop'), ('popular', 'Popular'), ('rock', 'Rock'), ('alternative rock', 'Alternative Rock'), ('country', 'Country'), ('pop', 'Pop'), ('classical', 'Classical'), ('rhythm and blues', 'Rhythm and Blues'), ('blues', 'Blues'), ('jazz', 'Jazz'), ('blues', 'Blues'), ('soul', 'Soul'), ('reggae', 'Reggae'), ('gospel', 'Gospel'), ('afrobeat', 'Afrobeat'), ('juju', 'Juju'), ('fuji', 'Fuji')], default='others', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
