# Generated by Django 4.0.6 on 2022-08-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0002_alter_song_options_song_album_song_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
